const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ui = require('./update_ui');
const elements = new Map();
function el(id) {
  if (!elements.has(id)) {
    const classes = new Set();
    elements.set(id,{style:{display:'none'},classList:{add(n){classes.add(n);},remove(n){classes.delete(n);},contains(n){return classes.has(n);},toggle(n,on){on=on===undefined?!classes.has(n):!!on;if(on)classes.add(n);else classes.delete(n);return on;}},listeners:{},addEventListener(n,f){this.listeners[n]=f;},removeAttribute(){},textContent:''});
  }
  return elements.get(id);
}
const calls=[]; let current={phase:'available',info:{current:'v2.2.6',latest:'v2.3.0',hasNew:true}};
const window = {SCEZUpdateUI:ui,GetUpdateState:()=>Promise.resolve(current),BeginUpdateCheck:()=>{calls.push('check');return Promise.resolve(current);},DownloadUpdate:()=>{calls.push('download');current={...current,phase:'downloading',message:'正在下载'};return Promise.resolve();},CancelUpdate:()=>{calls.push('cancel');return Promise.resolve();},InstallUpdate:(confirm)=>{calls.push(confirm?'confirm-install':'install');return Promise.resolve(confirm?{}:{needsConfirm:true,activeWindows:2});},DismissUpdateResult:()=>{calls.push('dismiss');current={...current};delete current.result;return Promise.resolve();},OpenURL:()=>Promise.resolve()};
const code=fs.readFileSync(__dirname+'/app.js','utf8');
const start=code.indexOf('  // ---------- 应用内更新：');
const end=code.indexOf('  // ---------- 参数状态机',start);
const context=vm.createContext({window,el,lastState:null,toast(){},setTimeout(){},setInterval(){}});
vm.runInContext(code.slice(start,end),context);
const tick=()=>new Promise(r=>setImmediate(r));
(async()=>{
  el('app-ver').listeners.click();await tick();await tick();
  assert.equal(el('update-download').style.display,'');
  el('update-download').listeners.click();await tick();await tick();
  assert.equal(el('update-cancel').style.display,'');
  context.renderUpdate({...current,downloaded:50,total:100});
  assert.equal(el('update-progress-bar').classList.contains('is-downloading'),true);
  context.renderUpdate({...current,phase:'validating',downloaded:100,total:100});
  assert.equal(el('update-progress-bar').classList.contains('is-downloading'),false);
  context.renderUpdate(current);
  el('update-close').listeners.click();assert.equal(el('update-modal').style.display,'none');assert.equal(calls.includes('cancel'),false);
  current={...current,phase:'ready',canInstall:true};el('app-ver').listeners.click();await tick();await tick();
  el('update-install').listeners.click();await tick();await tick();
  assert.equal(el('update-confirm').style.display,'');assert.match(el('update-confirm-text').textContent,/2 个投屏窗口/);
  el('update-confirm-cancel').listeners.click();assert.equal(calls.includes('confirm-install'),false);
  el('app-ver').listeners.click();await tick();await tick();el('update-install').listeners.click();await tick();await tick();el('update-confirm-ok').listeners.click();await tick();await tick();
  assert.equal(calls.includes('confirm-install'),true);
  current={phase:'available',info:{current:'v2.2.2',latest:'v2.2.2',hasNew:false},result:{ok:true,version:'v2.2.2'}};
  el('update-modal').style.display='none';
  context.renderUpdate(current);
  assert.equal(el('app-ver').classList.contains('has-new'),true);
  el('app-ver').listeners.click();await tick();await tick();
  assert.equal(el('update-result').style.display,'');
  assert.equal(el('app-ver').classList.contains('has-new'),false);
  el('update-later').listeners.click();await tick();await tick();
  assert.equal(calls.includes('dismiss'),true);
  el('app-ver').listeners.click();await tick();await tick();
  assert.equal(el('update-result').style.display,'none');
  assert.equal(el('app-ver').classList.contains('has-new'),false);
  el('update-close').listeners.click();await tick();
  current={phase:'available',info:{current:'v2.2.2',latest:'v2.3.1',hasNew:true}};
  context.renderUpdate(current);
  assert.equal(el('app-ver').classList.contains('has-new'),true);
  el('app-ver').listeners.click();await tick();await tick();
  el('update-close').listeners.click();await tick();await tick();
  context.renderUpdate(current);
  assert.equal(el('app-ver').classList.contains('has-new'),false);
  current={...current,info:{...current.info,latest:'v2.3.2'}};
  context.renderUpdate(current);
  assert.equal(el('app-ver').classList.contains('has-new'),true);
  current={phase:'available',info:{current:'v2.2.2',latest:'v2.2.2',hasNew:false},result:{ok:false,error:'synthetic install failure'}};
  const dismissCount=calls.filter(c=>c==='dismiss').length;
  el('app-ver').listeners.click();await tick();await tick();
  el('update-modal').listeners.click({target:el('update-modal')});await tick();await tick();
  assert.equal(calls.filter(c=>c==='dismiss').length,dismissCount);
  assert.equal(current.result.ok,false);
  console.log('update modal download, close, active casts and explicit install cases passed');
  console.log('success result, later new versions and failure retention cases passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
